name: 🚀 Feature Request
description: Create a new ticket for a new feature request
title: "🚀 [Feature Request] - Title"
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        🚀 **Feature Request**

        Thanks for taking the time to fill out this Feature Request report! :memo:

        :information_source: Before submitting the Issue, please make sure to read our Contributing Guidelines and Code Of Conduct. By submitting this issue, you agree to follow our guidelines. :book:

        :link: [CONTRIBUTING GUIDELINES](https://github.com/juhinagpure/Eduford-university/blob/master/Contributors.md)
        :link: [CODE OF CONDUCT](https://github.com/juhinagpure/Eduford-university/blob/master/CODE_OF_CONDUCT.md)
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem ? Please describe. ✍️
      description: Enter a brief description about the feature you feel is required.
      placeholder: Give all the context of your enhancement as well as the existing project.
      value: "Enhancement"
    validations:
      required: true
  - type: textarea
    id: solutionsteps
    attributes:
      label: Describe briefly how you would implement this enhancement.
      description: Please provide a solution steps for implementing the enhancement.
      placeholder: Short and explicit description of the solution steps...
      value: |
        Some steps to implement this enhancement-
        1. Step 1
        2. Step 2
        3. Step 3
      render: bash
    validations:
      required: true
  - type: textarea
    id: AdditionalInfo
    attributes:
      label: Additional context or screenshots
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add any other context or screenshots about the feature request here.
      value: "Additional context"
  - type: dropdown
    id: contribution
    attributes:
      label: Are you contributing for a program?
      multiple: true
      options:
        - GSSoC2024
        - Other
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contributing guidelines. Please read our [Contributing Guidelines](https://github.com/juhinagpure/Eduford-university/blob/master/Contributors.md).
      options:
        - label: I have read and agree to the Contributing Guidelines of this project.
          required: true+